#!/usr/bin/env python3
import sys
import os

import nltk

def main():
	if len(sys.argv) != 3:
		print("Usage: ./analyze file_to_analyze words")
		exit(1)
	
	sware_words = []
	with open(os.path.join(sys.path[0], sys.argv[2]), 'r') as word:
		line = word.readlineline()
		
		while len(line) > 0:
			sware_words += [line.strip()]
			line = word.readline()
			
	subtitle = []
	tokenized = []
	sware_words_counter = 0

	with open(os.path.join(sys.path[0], sys.argv[1]), 'r') as f:
		line = f.readline()
		
		while len(line) > 0:
			line = line.strip()
			tokenized = nltk.word_tokenize(line)
			for word in tokenized:
				if word in sware_words:
					print(word)
					sware_words_counter+=1

			line = f.readline()

	print("File has {} matched words".format(sware_words_counter))

if __name__ == "__main__":
	main()
